### ISSUE TITLE
WAIT!

### ISSUE THREAD

**Issue by ghost** [TruncatedDinosour/website#11]
wtf is this??? quote: "i want to end my life no even fucking joking"??? 87f169da9b90073f277649e8f8836823c9d876d3

text me https://see_you_already.t.me or just reply here.

**Comment by ar1ja** [comment]
im okay no worries
i was mid panic attack and shit was just bad lol
but i remembered i need to push changes to the favicon so naturally, me, who has iq below -10 did that

sorry

**Comment by ghost** [comment]
As long as you're okay 👍
