### ISSUE TITLE
issue with latest blog post

### ISSUE THREAD

**Issue by ayunami2000** [TruncatedDinosour/website#3]
hello,

please add comment box e.g. https://www.htmlcommentbox.com/ to your blog for user feedback.

thanks!

**Comment by ar1ja** [comment]
hey, thanks for the suggestion, but I want to keep my blog minimal and have no javascript on it :)
even the parts that have js will only have FOSS and/or javascript that is written by me ;)

Thanks for the suggestion, but I have to say no <3

**Comment by ar1ja** [comment]
Reopening this, I have gotten an idea to make comment.ari-web.xyz a thing :)

**Comment by ar1ja** [comment]
https://user.ari-web.xyz/ now exists
